import React from "react";
import {
  AlertCircle,
  AlertTriangle,
  ArrowDown,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  AtSign,
  Banknote,
  BarChart2,
  BookOpen,
  Building2,
  Camera,
  Car,
  Check,
  CheckCircle,
  ChevronLeft,
  ChevronRight,
  Clock,
  Code2,
  Diamond,
  Download,
  Edit,
  Eye,
  EyeOff,
  FileText,
  Fingerprint,
  Flag,
  Globe,
  Heart,
  Home,
  ImageIcon,
  Info,
  List,
  Lock,
  LogIn,
  LogOut,
  Mail,
  Map,
  MapPin,
  Megaphone,
  MessageCircle,
  Minus,
  MinusCircle,
  Moon,
  Navigation,
  Pencil,
  Phone,
  Plus,
  QrCode,
  Receipt,
  RefreshCw,
  Search,
  Send,
  Settings,
  Share2,
  Shield,
  ShieldCheck,
  Star,
  Sun,
  Tag,
  Timer,
  Trash2,
  TrendingUp,
  Upload,
  User,
  UserPlus,
  Users,
  Wallet,
  X,
  XCircle,
  Locate,
  Zap,
  CreditCard,
  Gauge,
} from "lucide-react-native";

type SvgIconProps = {
  size?: number;
  color?: string;
  strokeWidth?: number;
  style?: object;
};

type SvgIconComponent = React.ComponentType<SvgIconProps>;

const ICON_MAP: Record<string, SvgIconComponent> = {
  add: Plus,
  "alert-circle": AlertCircle,
  "alert-circle-outline": AlertCircle,
  "arrow-back": ArrowLeft,
  "arrow-down": ArrowDown,
  "arrow-forward": ArrowRight,
  at: AtSign,
  "bar-chart": BarChart2,
  "bar-chart-outline": BarChart2,
  "barcode-outline": QrCode,
  "business-outline": Building2,
  call: Phone,
  "call-outline": Phone,
  car: Car,
  "car-outline": Car,
  "car-sport": Car,
  "car-sport-outline": Car,
  card: CreditCard,
  "card-outline": CreditCard,
  cash: Banknote,
  "cash-outline": Banknote,
  chatbubble: MessageCircle,
  "chatbubble-ellipses": MessageCircle,
  "chatbubble-ellipses-outline": MessageCircle,
  checkmark: Check,
  "checkmark-circle": CheckCircle,
  "checkmark-circle-outline": CheckCircle,
  "chevron-back": ChevronLeft,
  "chevron-forward": ChevronRight,
  close: X,
  x: X,
  "close-circle": XCircle,
  "close-circle-outline": XCircle,
  "camera-outline": Camera,
  "cloud-upload-outline": Upload,
  "code-slash-outline": Code2,
  "create-outline": Edit,
  "diamond-outline": Diamond,
  "directions-car": Car,
  "document-outline": FileText,
  "document-text": FileText,
  "document-text-outline": FileText,
  "finger-print-outline": Fingerprint,
  "download-outline": Download,
  "eye-outline": Eye,
  "globe-outline": Globe,
  "image-outline": ImageIcon,
  "eye-off-outline": EyeOff,
  flag: Flag,
  "flag-outline": Flag,
  "flash-outline": Zap,
  heart: Heart,
  "heart-outline": Heart,
  home: Home,
  "home-outline": Home,
  "information-circle-outline": Info,
  "id-card-outline": CreditCard,
  "keypad-outline": List,
  "list-outline": List,
  "locate-outline": Locate,
  location: MapPin,
  "location-outline": MapPin,
  "lock-closed": Lock,
  "lock-closed-outline": Lock,
  "log-in-outline": LogIn,
  "log-out-outline": LogOut,
  "mail-outline": Mail,
  "map-outline": Map,
  "megaphone-outline": Megaphone,
  "menu-book": BookOpen,
  "moon-outline": Moon,
  navigate: Navigation,
  "navigate-outline": Navigation,
  pencil: Pencil,
  people: Users,
  "people-outline": Users,
  person: User,
  "person-add-outline": UserPlus,
  "person-outline": User,
  "pricetag-outline": Tag,
  "receipt-outline": Receipt,
  refresh: RefreshCw,
  "refresh-outline": RefreshCw,
  remove: Minus,
  "remove-circle": MinusCircle,
  "search-outline": Search,
  send: Send,
  speedometer: Gauge,
  "speedometer-outline": Gauge,
  settings: Settings,
  "settings-outline": Settings,
  "share-outline": Share2,
  shield: Shield,
  "shield-outline": Shield,
  "shield-checkmark": ShieldCheck,
  "shield-checkmark-outline": ShieldCheck,
  star: Star,
  "star-outline": Star,
  "sunny-outline": Sun,
  "swap-horizontal": ArrowLeftRight,
  "swap-horizontal-outline": ArrowLeftRight,
  time: Clock,
  "time-outline": Clock,
  timer: Timer,
  "timer-outline": Timer,
  "trash-outline": Trash2,
  "trending-up": TrendingUp,
  wallet: Wallet,
  "wallet-outline": Wallet,
  warning: AlertTriangle,
};

type IconComponentProps = {
  name: string;
  size?: number;
  color?: string;
  style?: object;
};

function AppIcon({ name, size = 24, color = "#000", style }: IconComponentProps) {
  const LucideIcon = ICON_MAP[name];
  if (!LucideIcon) {
    console.warn(`[AppIcon] Unknown icon name: "${name}"`);
    return <AlertCircle size={size} color={color} style={style} />;
  }
  return <LucideIcon size={size} color={color} style={style} />;
}

export const Ionicons = AppIcon;
export const MaterialIcons = AppIcon;
export const MaterialCommunityIcons = AppIcon;
export const Feather = AppIcon;
export default AppIcon;
